### ISSUE TITLE
problem: promote the project at chinese community and get some feedback

### ISSUE THREAD

**Issue by shaibearary** [Stackerstan/mindmachine#13]
simplest solution, add a chinese read me, but there could be more ways and have some sub problem of this problem

**Comment by shaibearary** [comment]
done in #15

**Comment by shaibearary** [comment]
children problem:

- [ ] translate super protecal, doki
- [ ] write and post introduction articals it on wechat public account/CSDN/8byte etc....

**Comment by stanstacks** [comment]
Sorry about the late merge @pqingshuang

**Comment by shaibearary** [comment]
no worries!

**Comment by shaibearary** [comment]
pubkey: cc8d072efdcc676fcbac14f6cd6825edc3576e55eb786a2a975ee034a6a026cb
Expense: 248888 Sats
