### ISSUE TITLE
problem: errors after dial tcp failed for nostr.688.org

### ISSUE THREAD

**Issue by gsovereignty** [Stackerstan/mindmachine#17]
There *is* a host and it's up (it connected to it immediately before this error).

WARN => failed to connect to wss://nostr.688.org: error opening websocket to 'wss://nostr.688.org': dial tcp: lookup nostr.688.org: no such host

ERROR => this should not happen
`/mindmachine/messaging/nostrelay/fetchEvents.go:177`

panic: runtime error: index out of range [0] with length 0
`/mindmachine/auxiliarium/protocol/handler.go:185`

**Comment by stanstacks** [comment]
probably fixed in #18
