### ISSUE TITLE
problem: chinese readme has simplified and traditional mixed together

### ISSUE THREAD

**Issue by gsovereignty** [Stackerstan/mindmachine#19]
problem: chinese readme has simplified and traditional mixed together

solution:
make it all simplified, or make it all traditional, or use both put keep them in separate documents 

ping @pqingshuang

**Comment by shaibearary** [comment]
@gazhayes 
Hi just make a new  patch would you mind help double check?

**Comment by shaibearary** [comment]
pubkey: cc8d072efdcc676fcbac14f6cd6825edc3576e55eb786a2a975ee034a6a026cb
Expense:  8 Sats
