### ISSUE TITLE
Problem: difficult to track expenses

### ISSUE THREAD

**Issue by stanstacks** [Stackerstan/mindmachine#7]
As Expenses are not implemented on the frontend yet, we need to track them somewhere else for now. 

When solving a problem with a pull request, post a comment including your stackerstan pubkey and also the total value of the time you spent, denominated in satoshi. That way you can get Shares (once I implement Expenses on the frontend).

So, take your usual hourly rate (or whatever you are happy with), calculate that in satoshi at the current Bitcoin price, and multiply by how long you spent on solving the issue.

### Example
E.g. US$50 an hour = 0.00297619 BTC = 297,619 Sats
2 hours * 297,619 = 595238 Sats

So post the following to this issue:
>pubkey: c913498571389....
>Expense: 595238 Sats
>Issue number: #6

**Comment by gsovereignty** [comment]
pubkey: 706a539b6cafe1dabde1b112d01aa6a6550edfea2f12ce1763f6e1a1b1424d45
Expense: 363636
#4

**Comment by shaibearary** [comment]
pubkey: cc8d072efdcc676fcbac14f6cd6825edc3576e55eb786a2a975ee034a6a026cb
Expense: 8 Sats
#19
